### ISSUE TITLE
Support stick-to-ground style option

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#61]
In some scenarios, it would be useful to see features directly on the ground rather than floating in the air. For these cases, we should support a new style flag like `stick-to-ground`, which makes polylines (and polygons?) flat on the terrain.

The usage in the style sheet would be like so:

```yaml
rules:
- geometry: ["lines"]
  stick-to-ground: true
```

Extending the support of this flag to polygons would be an optional extra for this issue.
