### ISSUE TITLE
Allow style subrule fallback list

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/erdblick#65]
Currently, all style rules from a style sheet are naively applied to all matching features. However, usually, it will be sufficient if only the first matching rule is applied, and there aren't multiple visualizations generated for the same feature. For this purpose, the `first-of` style rule field is introduced. It may be applied as follows:

```yaml
rules:
- type: Road
  first-of:
  - (subrule-1...)
  - (subrule-2...)
  - (subrule-n)
```

**Note:**
* Subrules may have further subrules
* All attributes except for `type` and `filter` are propagated from the parent rule to the subrules. For example, a parent rule `color` will be applied to the child.
